#
# >>> INPUT ZONE ---------------------------------
#

# Note: Date
start_date: "2015-10-01"
#start_date: "2019-10-01"
#start_date: "2024-10-01"
#end_date: '2024-01-01'

# Note: Capital
percentage_vol_target: 20
notional_trading_capital: 100000000

# Note: Weight
#instrument_weights:
#    IRON: 0.5
#    GOLD_micro: 0.5
instrument_weights:
  AUD_micro: 1
  BBCOMM: 1
  BRE: 1
  CAD2: 1
  CAD10: 1
  CAD_micro: 1
  CANOLA: 1
  COPPER-micro: 1
  CORN: 1
  CORN_mini: 1
  CRUDE_W_micro: 1
  ETHER-micro: 1
  EU-BANKS: 1
  EUR_micro: 1
  FTSECHINAA: 1
  GAS_US_mini: 1
  GBP_micro: 1
  GOLD_micro: 1
  IRON: 1
  JGB-SGX-mini: 1
  KRWUSD_mini: 1
  MILLWHEAT: 1
  MUMMY: 1
  MXP: 1
  RUSSELL: 1
  SOYBEAN_mini: 1
  US10: 1
  V2X: 1
  VIX_mini: 1
  WHEAT_mini: 1
  LEANHOG: 1
  LIVECOW: 1
  RICE: 1
  PLAT: 1
  SILVER: 1
  OAT: 1
  NASDAQ_micro: 1
  US5: 1
  SOYMEAL: 1
  ZAR: 1
  NZD: 1
  US2: 1
  SP500_micro: 1
#use_instrument_div_mult_estimates: True
instrument_div_multiplier: 1

# Note: Forecast
forecast_weights:
  breakout10: 0
  breakout20: 0
  breakout40: 0
  breakout80: 0.33
  breakout160: 0.33
  breakout320: 0.33

forecast_div_multiplier: 1.10

#
# DEFAULT ZONE ---------------------------------
#
trading_rules:
  breakout10:
     function: systems.provided.rules.breakout.breakout
     data:
         - "rawdata.get_daily_prices"
     other_args:
       lookback: 10
     forecast_scalars: 0.60
  breakout20:
     function: systems.provided.rules.breakout.breakout
     data:
         - "rawdata.get_daily_prices"
     other_args:
       lookback: 20
     forecast_scalars: 0.67
  breakout40:
     function: systems.provided.rules.breakout.breakout
     data:
         - "rawdata.get_daily_prices"
     other_args:
       lookback: 40
     forecast_scalars: 0.70
  breakout80:
     function: systems.provided.rules.breakout.breakout
     data:
         - "rawdata.get_daily_prices"
     other_args:
       lookback: 80
     forecast_scalars: 0.73
  breakout160:
     function: systems.provided.rules.breakout.breakout
     data:
         - "rawdata.get_daily_prices"
     other_args:
       lookback: 160
     forecast_scalars: 0.74
  breakout320:
     function: systems.provided.rules.breakout.breakout
     data:
         - "rawdata.get_daily_prices"
     other_args:
       lookback: 320
     forecast_scalars: 0.74


forecast_cap: 20.0

# Buffer
buffer_trade_to_edge: True
buffer_method: forecast
buffer_size: 0.10

# Capital
base_currency: "USD"
capital_multiplier:
   func: syscore.capital.full_compounding