trading_rules:
  ewmac2_8: # name of the rule
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 2
         Lslow: 8
     forecast_scalar: 12.1
  ewmac4_16:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 4
         Lslow: 16
     forecast_scalar: 8.53
  ewmac8_32:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 8
         Lslow: 32
     forecast_scalar: 5.95
  ewmac16_64:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 16
         Lslow: 64
     forecast_scalar: 4.1
  ewmac32_128:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 32
         Lslow: 128
     forecast_scalar: 2.79
  ewmac64_256:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 64
         Lslow: 256
     forecast_scalar: 1.91

# Cap individual rule forecasts
forecast_cap: 20.0


#forecast_weights:
#  ewmac2_8:   0.1667
#  ewmac4_16:  0.1667
#  ewmac8_32:  0.1667
#  ewmac16_64: 0.1667
#  ewmac32_128: 0.1667
#  ewmac64_256: 0.1667
#forecast_div_multiplier: 1.0

forecast_weights:
  ewmac2_8:   0
  ewmac4_16:  0
  ewmac8_32:  0
  ewmac16_64: 1
  ewmac32_128: 0
  ewmac64_256: 0
forecast_div_multiplier: 1.0

#
# Capital / accounting
#
percentage_vol_target: 20.0
notional_trading_capital: 50000
base_currency: "USD"
# Optional: lock the backtest start date if you want to align data windows
#start_date: "2020-01-01"
#end_date: "2024-01-01"

# Portfolio — equal instrument weights

instrument_weights:
  # FX (each = 1/35 ≈ 0.02857143)
  CAD_micro: 0.02857143
  AUD_micro: 0.02857143
  GBP_micro: 0.02857143
  SGD_mini: 0.02857143
  EUR_micro: 0.02857143

  # Ags (each = 1/35)
  CORN_mini: 0.02857143
  WHEAT_mini: 0.02857143
  BBCOMM: 0.02857143
  SOYBEAN_mini: 0.02857143
  MILLWHEAT: 0.02857143

  # Equity (each = 1/35)
  MUMMY: 0.02857143
  FTSECHINAA: 0.02857143
  HANGENT_mini: 0.02857143
  IBEX_mini: 0.02857143
  EUROSTX-SMALL: 0.02857143

  # Vol (each = 1/14 ≈ 0.07142857)
  VNKI: 0.07142857
  VIX_mini: 0.07142857

  # OilGas (each = 1/35)
  CRUDE_W_micro: 0.02857143
  GASOILINE_micro: 0.02857143
  GAS_US_mini: 0.02857143
  CRUDE_W_mini: 0.02857143
  GAS-LAST: 0.02857143

  # Metal (each = 1/35)
  ETHER-micro: 0.02857143
  IRON: 0.02857143
  STEEL: 0.02857143
  BITCOIN: 0.02857143
  GOLD_micro: 0.02857143

  # Bond (each = 1/35)
  CAD2: 0.02857143
  SARONA: 0.02857143
  BTP3: 0.02857143
  EURIBOR: 0.02857143
  EURIBOR-ICE: 0.02857143


# (Optional, but commonly used) Use estimated diversification across instruments
use_instrument_div_mult_estimates: True