#
# >>> INPUT ZONE ---------------------------------
#

# This will affect capital by portfolio multiplier
#start_date: "2019-10-01" #"2011-01-01" # Need to skip#
#start_date: "2024-10-01"
start_date: "2000-10-01"
# Capital correction
#
percentage_vol_target: 20
notional_trading_capital: 10000000

base_currency: "USD"
capital_multiplier:
   func: syscore.capital.full_compounding

instrument_weights:

  # 1. FX

  # EM
  MXP: 0.03
  KRWUSD_mini: 0.03
  BRE: 0.03

  # DEV
  GBP_micro: 0.02
  AUD_micro: 0.02
  EUR_micro: 0.02
  CAD_micro: 0.02

  # 2. Ags:

  # Grain
  CORN_mini: 0.008
  WHEAT_mini: 0.008
  CANOLA: 0.008
  SOYBEAN_mini: 0.008
  RICE: 0.008

  # Soft
  MILLWHEAT: 0.04

  # Meats
  LEANHOG: 0.02
  LIVECOW: 0.02

  # Index
  BBCOMM: 0.04

  # 3. OilGas: Oil,Gas, Product
  CRUDE_W_micro: 0.083
  GAS_US_mini: 0.083

  # 4. Metals: Industrial

  # Precious
  GOLD_micro: 0.03
  SILVER: 0.03
  PLAT: 0.03

  # Industrial
  IRON: 0.03
  COPPER-micro: 0.03

  # Crypto
  ETHER-micro: 0.06


  # 5. Bond: Asia

  # EU
  OAT: 0.06
  # US
  US10: 0.06

  # Asia
  JGB-SGX-mini: 0.06

  # 6. Equity: Asia

  # EU
  EU-BANKS: 0.06

  # US
  RUSSELL: 0.03
  NASDAQ_micro: 0.03

  # Asia
  MUMMY: 0.03
  FTSECHINAA: 0.033


use_instrument_div_mult_estimates: True
#instrument_div_multiplier: 2.1
forecast_weights:
  ewmac2_8:   0
  ewmac4_16:  0
  ewmac8_32:  0
  ewmac16_64: 0.33
  ewmac32_128: 0.33
  ewmac64_256: 0.33
forecast_div_multiplier: 1.08

#
# forecast combination
#

#
# DEFAULT ZONE ---------------------------------
#

#
# Trading rule
#
trading_rules:
  ewmac2_8:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 2
         Lslow: 8
     forecast_scalar: 10.6
  ewmac4_16:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 4
         Lslow: 16
     forecast_scalar: 7.5
  ewmac8_32:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 8
         Lslow: 32
     forecast_scalar: 5.3
  ewmac16_64:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 16
         Lslow: 64
     forecast_scalar: 3.75
  ewmac32_128:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 32
         Lslow: 128
     forecast_scalar: 2.65
  ewmac64_256:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 64
         Lslow: 256
     forecast_scalar: 1.87

forecast_cap: 20.0

# Rule grouping
rule_groups:
    ewmac_fast:
       - ewmac2_8
       - ewmac4_16
    ewmac_medium:
       - ewmac8_32
       - ewmac16_64
    ewmac_slow:
       - ewmac32_128
       - ewmac64_256
style_groups:
    trend:
        - ewmac_fast
        - ewmac_medium
        - ewmac_slow

# Buffer
buffer_trade_to_edge: True
buffer_method: forecast
buffer_size: 0.10

