#
# >>> INPUT ZONE ---------------------------------
#

# Note: Date
#start_date: '2012-01-01'
#end_date: '2024-01-01'

# Note: Capital
# Capital correction
#
percentage_vol_target: 20
notional_trading_capital: 45000

# Note: Weight
# Portfolio creation
#
instrument_weights:
    VIX_mini: 1

use_instrument_div_mult_estimates: True
#instrument_div_multiplier: 1

# Note: Forecast
# forecast combination
#
forecast_weights:
  ewmac2_8: 0.16
  ewmac4_16: 0.16
  ewmac8_32: 0.16
  ewmac16_64: 0.16
  ewmac32_128: 0.16
  ewmac64_256: 0.16

forecast_div_multiplier: 1




#
# DEFAULT ZONE ---------------------------------
#

trading_rules:
  ewmac2_8: # name of the rule
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 2
         Lslow: 8
     forecast_scalar: 12.1
  ewmac4_16:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 4
         Lslow: 16
     forecast_scalar: 8.53
  ewmac8_32:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 8
         Lslow: 32
     forecast_scalar: 5.95
  ewmac16_64:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 16
         Lslow: 64
     forecast_scalar: 4.1
  ewmac32_128:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 32
         Lslow: 128
     forecast_scalar: 2.79
  ewmac64_256:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 64
         Lslow: 256
     forecast_scalar: 1.91

forecast_cap: 20.0

# Buffer
buffer_trade_to_edge: True
buffer_method: forecast
buffer_size: 0.10

# Capital
base_currency: "USD"
capital_multiplier:
   func: syscore.capital.full_compounding