#
# >>> INPUT ZONE ---------------------------------
#
# THIS IS 40% EMA 40% Breakout, 20% Carry
# This will affect capital by portfolio multiplier
#start_date: "2019-10-01"
start_date: "2024-10-01"
#start_date: "2000-10-01"
#start_date: "2010-10-01"
# Capital correction
#
percentage_vol_target: 20
notional_trading_capital: 47000

base_currency: "USD"
capital_multiplier:
   func: syscore.capital.fixed_capital

instrument_weights:

  # 1. FX
  MXP: 0.10 # EM
  GBP_micro: 0.033   # DEV
  AUD_micro: 0.033

  # 2. Ags: Grain
  CORN_mini: 0.083
  WHEAT_mini: 0.083

  # 3. OilGas: Oil,Gas
  CRUDE_W_micro: 0.167

  # 4. Metals: Industrial
  IRON: 0.167

  # 5. Bond: Asia
  JGB-SGX-mini: 0.167

  # 6. Equity
  EU-BANKS: 0.083 # Europe
  MUMMY: 0.083 # Asia

#use_instrument_div_mult_estimates: True
#use_forecast_div_mult_estimates: True
instrument_div_multiplier: 2.2
#forecast_div_multiplier: 1

forecast_weights:

    # 1. FX
     AUD_micro:
      ewmac2_8: 0
      ewmac4_16: 0.08
      ewmac8_32: 0.08
      ewmac16_64: 0.08
      ewmac32_128: 0.08
      ewmac64_256: 0.08
      breakout10: 0
      breakout20: 0.08
      breakout40: 0.08
      breakout80: 0.08
      breakout160: 0.08
      breakout320: 0.08
      carry5: 0.05
      carry20: 0.05
      carry60: 0.05
      carry120: 0.05

     GBP_micro:
      ewmac2_8: 0
      ewmac4_16: 0.08
      ewmac8_32: 0.08
      ewmac16_64: 0.08
      ewmac32_128: 0.08
      ewmac64_256: 0.08
      breakout10: 0
      breakout20: 0.08
      breakout40: 0.08
      breakout80: 0.08
      breakout160: 0.08
      breakout320: 0.08
      carry5: 0.05
      carry20: 0.05
      carry60: 0.05
      carry120: 0.05

     MXP:
      ewmac2_8: 0
      ewmac4_16: 0.08
      ewmac8_32: 0.08
      ewmac16_64: 0.08
      ewmac32_128: 0.08
      ewmac64_256: 0.08
      breakout10: 0
      breakout20: 0.08
      breakout40: 0.08
      breakout80: 0.08
      breakout160: 0.08
      breakout320: 0.08
      carry5: 0.05
      carry20: 0.05
      carry60: 0.05
      carry120: 0.05

     CORN_mini:
      ewmac2_8: 0
      ewmac4_16: 0
      ewmac8_32: 0
      ewmac16_64: 0.13
      ewmac32_128: 0.13
      ewmac64_256: 0.13
      breakout10: 0
      breakout20: 0
      breakout40: 0
      breakout80: 0.13
      breakout160: 0.13
      breakout320: 0.13
      carry5: 0.05
      carry20: 0.05
      carry60: 0.05
      carry120: 0.05

     WHEAT_mini:
      ewmac2_8: 0
      ewmac4_16: 0
      ewmac8_32: 0.1
      ewmac16_64: 0.1
      ewmac32_128: 0.1
      ewmac64_256: 0.1
      breakout10: 0
      breakout20: 0
      breakout40: 0.1
      breakout80: 0.1
      breakout160: 0.1
      breakout320: 0.1
      carry5: 0.05
      carry20: 0.05
      carry60: 0.05
      carry120: 0.05

     CRUDE_W_micro:
      ewmac2_8: 0
      ewmac4_16: 0.08
      ewmac8_32: 0.08
      ewmac16_64: 0.08
      ewmac32_128: 0.08
      ewmac64_256: 0.08
      breakout10: 0
      breakout20: 0.08
      breakout40: 0.08
      breakout80: 0.08
      breakout160: 0.08
      breakout320: 0.08
      carry5: 0.05
      carry20: 0.05
      carry60: 0.05
      carry120: 0.05

     IRON:
      ewmac2_8: 0
      ewmac4_16: 0
      ewmac8_32: 0
      ewmac16_64: 0
      ewmac32_128: 0.16
      ewmac64_256: 0.16
      breakout10: 0
      breakout20: 0
      breakout40: 0
      breakout80: 0.16
      breakout160: 0.16
      breakout320: 0.16
      carry5: 0.05
      carry20: 0.05
      carry60: 0.05
      carry120: 0.05

     JGB-SGX-mini:
      ewmac2_8: 0
      ewmac4_16: 0.08
      ewmac8_32: 0.08
      ewmac16_64: 0.08
      ewmac32_128: 0.08
      ewmac64_256: 0.08
      breakout10: 0
      breakout20: 0.08
      breakout40: 0.08
      breakout80: 0.08
      breakout160: 0.08
      breakout320: 0.08
      carry5: 0.05
      carry20: 0.05
      carry60: 0.05
      carry120: 0.05

     MUMMY:
      ewmac2_8: 0
      ewmac4_16: 0
      ewmac8_32: 0.1
      ewmac16_64: 0.1
      ewmac32_128: 0.1
      ewmac64_256: 0.1
      breakout10: 0
      breakout20: 0
      breakout40: 0.1
      breakout80: 0.1
      breakout160: 0.1
      breakout320: 0.1
      carry5: 0.05
      carry20: 0.05
      carry60: 0.05
      carry120: 0.05

     EU-BANKS:
      ewmac2_8: 0
      ewmac4_16: 0.08
      ewmac8_32: 0.08
      ewmac16_64: 0.08
      ewmac32_128: 0.08
      ewmac64_256: 0.08
      breakout10: 0
      breakout20: 0.08
      breakout40: 0.08
      breakout80: 0.08
      breakout160: 0.08
      breakout320: 0.08
      carry5: 0.05
      carry20: 0.05
      carry60: 0.05
      carry120: 0.05
forecast_div_multiplier:

    # FX
    MXP: 1.41
    AUD_micro: 1.41
    GBP_micro: 1.41

    # Ags
    CORN_mini: 1.35
    WHEAT_mini: 1.38

    # Oil & Gas
    CRUDE_W_micro: 1.41

    # Metals
    IRON: 1.34

    # Bond
    JGB-SGX-mini: 1.41

    # Equity
    EU-BANKS: 1.41
    MUMMY: 1.38

#
# DEFAULT ZONE ---------------------------------
#

#
# Trading rule
#
trading_rules:
  breakout10:
     function: systems.provided.rules.breakout.breakout
     data:
         - "rawdata.get_daily_prices"
     other_args:
       lookback: 10
     forecast_scalars: 0.60
  breakout20:
     function: systems.provided.rules.breakout.breakout
     data:
         - "rawdata.get_daily_prices"
     other_args:
       lookback: 20
     forecast_scalars: 0.67
  breakout40:
     function: systems.provided.rules.breakout.breakout
     data:
         - "rawdata.get_daily_prices"
     other_args:
       lookback: 40
     forecast_scalars: 0.70
  breakout80:
     function: systems.provided.rules.breakout.breakout
     data:
         - "rawdata.get_daily_prices"
     other_args:
       lookback: 80
     forecast_scalars: 0.73
  breakout160:
     function: systems.provided.rules.breakout.breakout
     data:
         - "rawdata.get_daily_prices"
     other_args:
       lookback: 160
     forecast_scalars: 0.74
  breakout320:
     function: systems.provided.rules.breakout.breakout
     data:
         - "rawdata.get_daily_prices"
     other_args:
       lookback: 320
     forecast_scalars: 0.74

  carry5:
    function: systems.provided.rules.carry.carry
    data:
      - "rawdata.raw_carry"
    other_args:
      smooth_days: 5
    forecast_scalar: 30

  carry20:
    function: systems.provided.rules.carry.carry
    data:
      - "rawdata.raw_carry"
    other_args:
      smooth_days: 20
    forecast_scalar: 30

  carry60:
    function: systems.provided.rules.carry.carry
    data:
      - "rawdata.raw_carry"
    other_args:
      smooth_days: 60
    forecast_scalar: 30

  carry120:
    function: systems.provided.rules.carry.carry
    data:
      - "rawdata.raw_carry"
    other_args:
      smooth_days: 120
    forecast_scalar: 30

  ewmac2_8:
    function: systems.provided.rules.ewmac.ewmac
    data:
      - "rawdata.get_daily_prices"
      - "rawdata.daily_returns_volatility"
    other_args:
      Lfast: 2
      Lslow: 8
    forecast_scalar: 10.6
  ewmac4_16:
    function: systems.provided.rules.ewmac.ewmac
    data:
      - "rawdata.get_daily_prices"
      - "rawdata.daily_returns_volatility"
    other_args:
      Lfast: 4
      Lslow: 16
    forecast_scalar: 7.5
  ewmac8_32:
    function: systems.provided.rules.ewmac.ewmac
    data:
      - "rawdata.get_daily_prices"
      - "rawdata.daily_returns_volatility"
    other_args:
      Lfast: 8
      Lslow: 32
    forecast_scalar: 5.3
  ewmac16_64:
    function: systems.provided.rules.ewmac.ewmac
    data:
      - "rawdata.get_daily_prices"
      - "rawdata.daily_returns_volatility"
    other_args:
      Lfast: 16
      Lslow: 64
    forecast_scalar: 3.75
  ewmac32_128:
    function: systems.provided.rules.ewmac.ewmac
    data:
      - "rawdata.get_daily_prices"
      - "rawdata.daily_returns_volatility"
    other_args:
      Lfast: 32
      Lslow: 128
    forecast_scalar: 2.65
  ewmac64_256:
    function: systems.provided.rules.ewmac.ewmac
    data:
      - "rawdata.get_daily_prices"
      - "rawdata.daily_returns_volatility"
    other_args:
      Lfast: 64
      Lslow: 256
    forecast_scalar: 1.87

forecast_cap: 20.0


# Buffer
buffer_trade_to_edge: True
buffer_method: forecast
buffer_size: 0.10

# Risk ovarlay (IDM of 2.2/ CSV since 2018)
#risk_overlay:
#  max_risk_fraction_normal_risk: 1.5 # Or 30%
#  max_risk_fraction_stdev_risk: 3.75 # Or 75%
#  max_risk_limit_sum_abs_risk: 3.25 # Or 65%
#  max_risk_leverage: 12 # From backtest
