#
# >>> INPUT ZONE ---------------------------------
#

# This will affect capital by portfolio multiplier
#start_date: "2019-10-01"
start_date: "2024-10-01"
#start_date: "2000-10-01"
#start_date: "2010-10-01"
# Capital correction
#
percentage_vol_target: 20
notional_trading_capital: 47000

base_currency: "USD"
capital_multiplier:
   func: syscore.capital.fixed_capital

instrument_weights:

  # 1. FX
  MXP: 0.10 # EM
  GBP_micro: 0.033   # DEV
  AUD_micro: 0.033

  # 2. Ags: Grain
  CORN_mini: 0.083
  WHEAT_mini: 0.083

  # 3. OilGas: Oil,Gas
  CRUDE_W_micro: 0.167

  # 4. Metals: Industrial
  IRON: 0.167

  # 5. Bond: Asia
  JGB-SGX-mini: 0.167

  # 6. Equity
  EU-BANKS: 0.083 # Europe
  MUMMY: 0.083 # Asia

#use_instrument_div_mult_estimates: True
instrument_div_multiplier: 2.2

forecast_weights:

    # 1. FX
     AUD_micro:
      carry5: 0.25
      carry20: 0.25
      carry60: 0.25
      carry120: 0.25
     GBP_micro:
      carry5: 0.25
      carry20: 0.25
      carry60: 0.25
      carry120: 0.25
     MXP:
      carry5: 0.25
      carry20: 0.25
      carry60: 0.25
      carry120: 0.25

     CORN_mini:
      carry5: 0.25
      carry20: 0.25
      carry60: 0.25
      carry120: 0.25
     WHEAT_mini:
      carry5: 0.25
      carry20: 0.25
      carry60: 0.25
      carry120: 0.25

     CRUDE_W_micro:
      carry5: 0.25
      carry20: 0.25
      carry60: 0.25
      carry120: 0.25
     IRON:
      carry5: 0.25
      carry20: 0.25
      carry60: 0.25
      carry120: 0.25

     JGB-SGX-mini:
      carry5: 0.25
      carry20: 0.25
      carry60: 0.25
      carry120: 0.25
     MUMMY:
      carry5: 0.25
      carry20: 0.25
      carry60: 0.25
      carry120: 0.25
     EU-BANKS:
      carry5: 0.25
      carry20: 0.25
      carry60: 0.25
      carry120: 0.25
forecast_div_multiplier:

    # FX
    MXP: 1.04
    AUD_micro: 1.04
    GBP_micro: 1.04

    # Ags
    CORN_mini: 1.04
    WHEAT_mini: 1.04

    # Oil & Gas
    CRUDE_W_micro: 1.04

    # Metals
    IRON: 1.04

    # Bond
    JGB-SGX-mini: 1.04

    # Equity
    EU-BANKS: 1.04
    MUMMY: 1.04

#
# DEFAULT ZONE ---------------------------------
#

#
# Trading rule
#
trading_rules:
  carry5:
    function: systems.provided.rules.carry.carry
    data:
      - "rawdata.raw_carry"
    other_args:
      smooth_days: 5
    forecast_scalar: 30

  carry20:
    function: systems.provided.rules.carry.carry
    data:
      - "rawdata.raw_carry"
    other_args:
      smooth_days: 20
    forecast_scalar: 30

  carry60:
    function: systems.provided.rules.carry.carry
    data:
      - "rawdata.raw_carry"
    other_args:
      smooth_days: 60
    forecast_scalar: 30

  carry120:
    function: systems.provided.rules.carry.carry
    data:
      - "rawdata.raw_carry"
    other_args:
      smooth_days: 120
    forecast_scalar: 30

forecast_cap: 20.0


# Buffer
buffer_trade_to_edge: True
buffer_method: forecast
buffer_size: 0.10

# Risk ovarlay (IDM of 2.2/ CSV since 2018)
#risk_overlay:
#  max_risk_fraction_normal_risk: 1.5 # Or 30%
#  max_risk_fraction_stdev_risk: 3.75 # Or 75%
#  max_risk_limit_sum_abs_risk: 3.25 # Or 65%
#  max_risk_leverage: 12 # From backtest
