#
# >>> INPUT ZONE ---------------------------------
#

# This will affect capital by portfolio multiplier
#start_date: "2019-10-01"
start_date: "2024-10-01"
#start_date: "2000-10-01"
#start_date: "2010-10-01"
# Capital correction
#
percentage_vol_target: 20
notional_trading_capital: 47000

base_currency: "USD"
capital_multiplier:
   func: syscore.capital.fixed_capital

instrument_weights:

  # 1. FX
  MXP: 0.10 # EM
  GBP_micro: 0.033   # DEV
  AUD_micro: 0.033

  # 2. Ags: Grain
  CORN_mini: 0.083
  WHEAT_mini: 0.083

  # 3. OilGas: Oil,Gas
  CRUDE_W_micro: 0.167

  # 4. Metals: Industrial
  IRON: 0.167

  # 5. Bond: Asia
  JGB-SGX-mini: 0.167

  # 6. Equity
  EU-BANKS: 0.083 # Europe
  MUMMY: 0.083 # Asia

#use_instrument_div_mult_estimates: True
#use_forecast_div_mult_estimates: True
instrument_div_multiplier: 2.2
#forecast_div_multiplier: 1

forecast_weights:

    # 1. FX
     AUD_micro:
      breakout10: 0
      breakout20: 0.2
      breakout40: 0.2
      breakout80: 0.2
      breakout160: 0.2
      breakout320: 0.2
     GBP_micro:
      breakout10: 0
      breakout20: 0.2
      breakout40: 0.2
      breakout80: 0.2
      breakout160: 0.2
      breakout320: 0.2
     MXP:
      breakout10: 0
      breakout20: 0.2
      breakout40: 0.2
      breakout80: 0.2
      breakout160: 0.2
      breakout320: 0.2

     CORN_mini:
      breakout10: 0
      breakout20: 0
      breakout40: 0
      breakout80: 0.33
      breakout160: 0.33
      breakout320: 0.33
     WHEAT_mini:
      breakout10: 0
      breakout20: 0
      breakout40: 0.25
      breakout80: 0.25
      breakout160: 0.25
      breakout320: 0.25

     CRUDE_W_micro:
      breakout10: 0
      breakout20: 0.2
      breakout40: 0.2
      breakout80: 0.2
      breakout160: 0.2
      breakout320: 0.2
     IRON:
      breakout10: 0
      breakout20: 0
      breakout40: 0
      breakout80: 0.33
      breakout160: 0.33
      breakout320: 0.33

     JGB-SGX-mini:
      breakout10: 0
      breakout20: 0.2
      breakout40: 0.2
      breakout80: 0.2
      breakout160: 0.2
      breakout320: 0.2
     MUMMY:
      breakout10: 0
      breakout20: 0
      breakout40: 0.25
      breakout80: 0.25
      breakout160: 0.25
      breakout320: 0.25
     EU-BANKS:
      breakout10: 0
      breakout20: 0.2
      breakout40: 0.2
      breakout80: 0.2
      breakout160: 0.2
      breakout320: 0.2
forecast_div_multiplier:

    # FX
    MXP: 1.17
    AUD_micro: 1.24
    GBP_micro: 1.24

    # Ags
    CORN_mini: 1.10
    WHEAT_mini: 1.17

    # Oil & Gas
    CRUDE_W_micro: 1.24

    # Metals
    IRON: 1.07

    # Bond
    JGB-SGX-mini: 1.24

    # Equity
    EU-BANKS: 1.24
    MUMMY: 1.17

#
# DEFAULT ZONE ---------------------------------
#

#
# Trading rule
#
trading_rules:
  breakout10:
     function: systems.provided.rules.breakout.breakout
     data:
         - "rawdata.get_daily_prices"
     other_args:
       lookback: 10
     forecast_scalars: 0.60
  breakout20:
     function: systems.provided.rules.breakout.breakout
     data:
         - "rawdata.get_daily_prices"
     other_args:
       lookback: 20
     forecast_scalars: 0.67
  breakout40:
     function: systems.provided.rules.breakout.breakout
     data:
         - "rawdata.get_daily_prices"
     other_args:
       lookback: 40
     forecast_scalars: 0.70
  breakout80:
     function: systems.provided.rules.breakout.breakout
     data:
         - "rawdata.get_daily_prices"
     other_args:
       lookback: 80
     forecast_scalars: 0.73
  breakout160:
     function: systems.provided.rules.breakout.breakout
     data:
         - "rawdata.get_daily_prices"
     other_args:
       lookback: 160
     forecast_scalars: 0.74
  breakout320:
     function: systems.provided.rules.breakout.breakout
     data:
         - "rawdata.get_daily_prices"
     other_args:
       lookback: 320
     forecast_scalars: 0.74

forecast_cap: 20.0


# Buffer
buffer_trade_to_edge: True
buffer_method: forecast
buffer_size: 0.10

# Risk ovarlay (IDM of 2.2/ CSV since 2018)
#risk_overlay:
#  max_risk_fraction_normal_risk: 1.5 # Or 30%
#  max_risk_fraction_stdev_risk: 3.75 # Or 75%
#  max_risk_limit_sum_abs_risk: 3.25 # Or 65%
#  max_risk_leverage: 12 # From backtest

