trading_rules:
  breakout10:
     function: systems.provided.rules.breakout.breakout
     data:
         - "rawdata.get_daily_prices"
     other_args:
       lookback: 10
     forecast_scalars: 0.60
  breakout20:
     function: systems.provided.rules.breakout.breakout
     data:
         - "rawdata.get_daily_prices"
     other_args:
       lookback: 20
     forecast_scalars: 0.67
  breakout40:
     function: systems.provided.rules.breakout.breakout
     data:
         - "rawdata.get_daily_prices"
     other_args:
       lookback: 40
     forecast_scalars: 0.70
  breakout80:
     function: systems.provided.rules.breakout.breakout
     data:
         - "rawdata.get_daily_prices"
     other_args:
       lookback: 80
     forecast_scalars: 0.73
  breakout160:
     function: systems.provided.rules.breakout.breakout
     data:
         - "rawdata.get_daily_prices"
     other_args:
       lookback: 160
     forecast_scalars: 0.74
  breakout320:
     function: systems.provided.rules.breakout.breakout
     data:
         - "rawdata.get_daily_prices"
     other_args:
       lookback: 320
     forecast_scalars: 0.74

forecast_cap: 20.0


### INPUT -----------------------------------------------------------------
forecast_weights:
     S50:
      breakout10: 0
      breakout20: 0
      breakout40: 0.25
      breakout80: 0.25
      breakout160: 0.25
      breakout320: 0.25
     USD:
      breakout10: 0
      breakout20: 0
      breakout40: 0
      breakout80: 0.33
      breakout160: 0.33
      breakout320: 0.33
     GF10:
      breakout10: 0
      breakout20: 0
      breakout40: 0.25
      breakout80: 0.25
      breakout160: 0.25
      breakout320: 0.25
     EURUSD:
      breakout10: 0
      breakout20: 0
      breakout40: 0
      breakout80: 0.33
      breakout160: 0.33
      breakout320: 0.33
     SVF:
      breakout10: 0
      breakout20: 0
      breakout40: 0.25
      breakout80: 0.25
      breakout160: 0.25
      breakout320: 0.25
     USDJPY:
      breakout10: 0
      breakout20: 0
      breakout40: 0
      breakout80: 0.33
      breakout160: 0.33
      breakout320: 0.33
forecast_div_multiplier:
     S50: 1.17
     USD: 1.10
     GF10: 1.17
     EURUSD: 1.10
     SVF: 1.17
     USDJPY: 1.10
#
# Capital correction
#
percentage_vol_target: 14
notional_trading_capital: 2495652.2
base_currency: "USD"

capital_multiplier:
   func: syscore.capital.full_compounding
#
# Portfolio creation
#
instrument_weights:

    # Equity
    S50: 0.33

    # Metals
    GF10: 0.165
    SVF: 0.165

    # FX
    USD: 0.11 # EM
    EURUSD: 0.11 # DEV
    USDJPY: 0.11 # DEV

#instrument_div_multiplier: 1.48
use_instrument_div_mult_estimates: True  #TEMP

rule_groups:
    ewmac_fast:
       - ewmac2_8
       - ewmac4_16
    ewmac_medium:
       - ewmac8_32
       - ewmac16_64
    ewmac_slow:
       - ewmac32_128
       - ewmac64_256
style_groups:
    trend:
        - ewmac_fast
        - ewmac_medium
        - ewmac_slow

# Buffer
buffer_trade_to_edge: True
buffer_method: forecast
buffer_size: 0.1
vol_normalise_currency_costs: False # Need to set to false for System F1



#start_date: "2000-10-01"
start_date: "2024-10-01"
#start_date: "2019-10-01"
