trading_rules:
  carry5:
    function: systems.provided.rules.carry.carry
    data:
      - "rawdata.raw_carry"
    other_args:
      smooth_days: 5
    forecast_scalar: 30

  carry20:
    function: systems.provided.rules.carry.carry
    data:
      - "rawdata.raw_carry"
    other_args:
      smooth_days: 20
    forecast_scalar: 30

  carry60:
    function: systems.provided.rules.carry.carry
    data:
      - "rawdata.raw_carry"
    other_args:
      smooth_days: 60
    forecast_scalar: 30

  carry120:
    function: systems.provided.rules.carry.carry
    data:
      - "rawdata.raw_carry"
    other_args:
      smooth_days: 120
    forecast_scalar: 30

forecast_cap: 20.0


### INPUT -----------------------------------------------------------------
forecast_weights:
     S50:
        carry5: 0
        carry20: 0.33
        carry60: 0.33
        carry120: 0.33

     USD:
        carry5: 0
        carry20: 0.33
        carry60: 0.33
        carry120: 0.33

     GF10:
        carry5: 0
        carry20: 0.33
        carry60: 0.33
        carry120: 0.33

     EURUSD:
        carry5: 0
        carry20: 0.33
        carry60: 0.33
        carry120: 0.33

     SVF:
        carry5: 0
        carry20: 0.33
        carry60: 0.33
        carry120: 0.33

     USDJPY:
        carry5: 0
        carry20: 0.33
        carry60: 0.33
        carry120: 0.33



forecast_div_multiplier:
     S50: 1.04
     USD: 1.04
     GF10: 1.04
     EURUSD: 1.04
     SVF: 1.04
     USDJPY: 1.04
#
# Capital correction
#
percentage_vol_target: 14
notional_trading_capital: 2495652.2
base_currency: "USD"

capital_multiplier:
   func: syscore.capital.full_compounding
#
# Portfolio creation
#
instrument_weights:

    # Equity
    S50: 0.33

    # Metals
    GF10: 0.165
    SVF: 0.165

    # FX
    USD: 0.11 # EM
    EURUSD: 0.11 # DEV
    USDJPY: 0.11 # DEV

#instrument_div_multiplier: 1.48
use_instrument_div_mult_estimates: True  #TEMP

rule_groups:
    ewmac_fast:
       - ewmac2_8
       - ewmac4_16
    ewmac_medium:
       - ewmac8_32
       - ewmac16_64
    ewmac_slow:
       - ewmac32_128
       - ewmac64_256
style_groups:
    trend:
        - ewmac_fast
        - ewmac_medium
        - ewmac_slow

# Buffer
buffer_trade_to_edge: True
buffer_method: forecast
buffer_size: 0.1
vol_normalise_currency_costs: False # Need to set to false for System F1



#start_date: "2000-10-01"
#start_date: "2024-10-01"
#start_date: "2019-10-01"

