trading_rules:
  ewmac2_8: # name of the rule
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 2
         Lslow: 8
     forecast_scalar: 10.6
  ewmac4_16:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 4
         Lslow: 16
     forecast_scalar: 7.5
  ewmac8_32:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 8
         Lslow: 32
     forecast_scalar: 5.3
  ewmac16_64:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 16
         Lslow: 64
     forecast_scalar: 3.75
  ewmac32_128:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 32
         Lslow: 128
     forecast_scalar: 2.65
  ewmac64_256:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 64
         Lslow: 256
     forecast_scalar: 1.87

forecast_cap: 20.0

### INPUT -----------------------------------------------------------------
forecast_weights:
     CAD10:
        ewmac2_8: 0.167
        ewmac4_16: 0.167
        ewmac8_32: 0.167
        ewmac16_64: 0.167
        ewmac32_128: 0.167
        ewmac64_256: 0.167
     EUR_micro:
        ewmac2_8: 0.167
        ewmac4_16: 0.167
        ewmac8_32: 0.167
        ewmac16_64: 0.167
        ewmac32_128: 0.167
        ewmac64_256: 0.167
     COPPER-micro:
        ewmac2_8: 0
        ewmac4_16: 0.2
        ewmac8_32: 0.2
        ewmac16_64: 0.2
        ewmac32_128: 0.2
        ewmac64_256: 0.2
     CORN_mini:
       ewmac2_8: 0
       ewmac4_16: 0
       ewmac8_32: 0.25 # From this
       ewmac16_64: 0.25
       ewmac32_128: 0.25
       ewmac64_256: 0.25
     CRUDE_W_micro:
       ewmac2_8: 0.167
       ewmac4_16: 0.167
       ewmac8_32: 0.167
       ewmac16_64: 0.167
       ewmac32_128: 0.167
       ewmac64_256: 0.167
     MUMMY:
        ewmac2_8: 0
        ewmac4_16: 0
        ewmac8_32: 0.25 # From this
        ewmac16_64: 0.25
        ewmac32_128: 0.25
        ewmac64_256: 0.25
     VIX_mini:
       ewmac2_8: 0
       ewmac4_16: 0
       ewmac8_32: 0
       ewmac16_64: 0
       ewmac32_128: 0
       ewmac64_256: 1

     CAD_micro:
       ewmac2_8: 0
       ewmac4_16: 0.2
       ewmac8_32: 0.2
       ewmac16_64: 0.2
       ewmac32_128: 0.2
       ewmac64_256: 0.2
     RUSSELL:
       ewmac2_8: 0.167
       ewmac4_16: 0.167
       ewmac8_32: 0.167
       ewmac16_64: 0.167
       ewmac32_128: 0.167
       ewmac64_256: 0.167
     BBCOMM:
       ewmac2_8: 0
       ewmac4_16: 0
       ewmac8_32: 0
       ewmac16_64: 0.33
       ewmac32_128: 0.33
       ewmac64_256: 0.33
forecast_div_multiplier:

     EUR_micro: 1.26
     CAD_micro: 1.19

     MUMMY: 1.13
     RUSSELL: 1.26

     CORN_mini: 1.13
     BBCOMM: 1.08

     VIX_mini: 1
     CRUDE_W_micro: 1.26
     COPPER-micro: 1.19
     CAD10: 1.26






#
# Capital correction
#
percentage_vol_target: 20
notional_trading_capital: 55000
base_currency: "USD"
capital_multiplier:
   func: syscore.capital.full_compounding
#
# Portfolio creation
#
instrument_weights:
    EUR_micro: 0.071
    CAD_micro: 0.071

    MUMMY: 0.071
    RUSSELL: 0.071

    CORN_mini: 0.071
    BBCOMM: 0.071

    VIX_mini: 0.143
    CRUDE_W_micro: 0.143
    COPPER-micro: 0.143
    CAD10: 0.143
#instrument_div_multiplier: 1.56
use_instrument_div_mult_estimates: True

rule_groups:
    ewmac_fast:
       - ewmac2_8
       - ewmac4_16
    ewmac_medium:
       - ewmac8_32
       - ewmac16_64
    ewmac_slow:
       - ewmac32_128
       - ewmac64_256
style_groups:
    trend:
        - ewmac_fast
        - ewmac_medium
        - ewmac_slow

#start_date: "2018-01-01" #"2011-01-01"

# Buffer
buffer_trade_to_edge: True
buffer_method: forecast
buffer_size: 0.10
vol_normalise_currency_costs: True # Need to set to false for System F1
