trading_rules:
  ewmac2_8: # name of the rule
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 2
         Lslow: 8
     forecast_scalar: 12.1
  ewmac4_16:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 4
         Lslow: 16
     forecast_scalar: 8.53
  ewmac8_32:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 8
         Lslow: 32
     forecast_scalar: 5.95
  ewmac16_64:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 16
         Lslow: 64
     forecast_scalar: 4.1
  ewmac32_128:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 32
         Lslow: 128
     forecast_scalar: 2.79
  ewmac64_256:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 64
         Lslow: 256
     forecast_scalar: 1.91

forecast_cap: 20.0

### INPUT -----------------------------------------------------------------
forecast_weights:
     CAD10:
        ewmac2_8: 0.167
        ewmac4_16: 0.167
        ewmac8_32: 0.167
        ewmac16_64: 0.167
        ewmac32_128: 0.167
        ewmac64_256: 0.167
     EUR_micro:
        ewmac2_8: 0
        ewmac4_16: 0.2
        ewmac8_32: 0.2
        ewmac16_64: 0.2
        ewmac32_128: 0.2
        ewmac64_256: 0.2
     CORN_mini:
       ewmac2_8: 0
       ewmac4_16: 0
       ewmac8_32: 0
       ewmac16_64: 0.33
       ewmac32_128: 0.33
       ewmac64_256: 0.33
     CAD_micro:
       ewmac2_8: 0
       ewmac4_16: 0.2
       ewmac8_32: 0.2
       ewmac16_64: 0.2
       ewmac32_128: 0.2
       ewmac64_256: 0.2
     BBCOMM:
       ewmac2_8: 0
       ewmac4_16: 0
       ewmac8_32: 0
       ewmac16_64: 0
       ewmac32_128: 0.5
       ewmac64_256: 0.5
forecast_div_multiplier:

     EUR_micro: 1.19
     CAD_micro: 1.19
     CORN_mini: 1.08
     BBCOMM: 1.03
     CAD10: 1.26

#
# Capital correction
#
percentage_vol_target: 20
notional_trading_capital: 54128.50
base_currency: "USD"
capital_multiplier:
   func: syscore.capital.fixed_capital
#
# Portfolio creation
#
instrument_weights:
    EUR_micro: 0.2
    CAD_micro: 0.2
    CORN_mini: 0.2
    BBCOMM: 0.2
    CAD10: 0.2
instrument_div_multiplier: 1.7
#use_instrument_div_mult_estimates: True

rule_groups:
    ewmac_fast:
       - ewmac2_8
       - ewmac4_16
    ewmac_medium:
       - ewmac8_32
       - ewmac16_64
    ewmac_slow:
       - ewmac32_128
       - ewmac64_256
style_groups:
    trend:
        - ewmac_fast
        - ewmac_medium
        - ewmac_slow

start_date: "2013-01-01" #"2011-01-01"

# Buffer
buffer_trade_to_edge: True
buffer_method: forecast
buffer_size: 0.10
#vol_normalise_currency_costs: True # Need to set to false for System F1
