#
# >>> INPUT ZONE ---------------------------------
#

# This will affect capital by portfolio multiplier
start_date: '2000-01-01'
#
# Capital correction
#
percentage_vol_target: 20
notional_trading_capital: 100000
base_currency: "USD"
capital_multiplier:
   func: syscore.capital.full_compounding
#
# Portfolio creation
#
instrument_weights:

    # Metals
    GOLD_micro: 0.06

    # Equity
    KOSPI_mini: 0.06
    NASDAQ_micro: 0.06

    # Bond
    SHATZ: 0.06
    US2: 0.06
    KR3: 0.06
    BTP: 0.06
    KR10: 0.06

    # FX
    NZD: 0.06
    JPY: 0.06
    MXP: 0.06
    GBP: 0.06
    # Ags
    LEANHOG: 0.06

    # OilGas
    GAS_US_mini: 0.06
    CRUDE_W_mini: 0.06

    # Vol
    V2X: 0.06


use_instrument_div_mult_estimates: True
#instrument_div_multiplier: 2.1

#
# forecast combination
#
forecast_weights:

# Expensive
  ewmac2_8: 0
  ewmac4_16: 0
  ewmac8_32: 0
  ewmac16_64: 0.33
  ewmac32_128: 0.33
  ewmac64_256: 0.33

forecast_div_multiplier: 1
#
# DEFAULT ZONE ---------------------------------
#

#
# Trading rule
#
trading_rules:
  ewmac2_8:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 2
         Lslow: 8
     forecast_scalar: 10.6
  ewmac4_16:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 4
         Lslow: 16
     forecast_scalar: 7.5
  ewmac8_32:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 8
         Lslow: 32
     forecast_scalar: 5.3
  ewmac16_64:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 16
         Lslow: 64
     forecast_scalar: 3.75
  ewmac32_128:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 32
         Lslow: 128
     forecast_scalar: 2.65
  ewmac64_256:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 64
         Lslow: 256
     forecast_scalar: 1.87

forecast_cap: 20.0

# Rule grouping
rule_groups:
    ewmac_fast:
       - ewmac2_8
       - ewmac4_16
    ewmac_medium:
       - ewmac8_32
       - ewmac16_64
    ewmac_slow:
       - ewmac32_128
       - ewmac64_256
style_groups:
    trend:
        - ewmac_fast
        - ewmac_medium
        - ewmac_slow

# Buffer
buffer_trade_to_edge: True
buffer_method: forecast
buffer_size: 0.10

