#
# >>> INPUT ZONE ---------------------------------
#

# This will affect capital by portfolio multiplier
#start_date: '2020-01-01'
#
# Capital correction
#
percentage_vol_target: 20
notional_trading_capital: 50000
base_currency: "USD"
capital_multiplier:
   func: syscore.capital.full_compounding
#
# Portfolio creation
#
#instrument_weights:
#  BITCOIN: 0.045
#  BRE: 0.045
#  COPPER-micro: 0.045
#  DAX: 0.045
#  DOW: 0.045
#  EU-BANKS: 0.045
#  EU-OIL: 0.045
#  EU-REALESTATE: 0.045
#  EUR_micro: 0.045
#  FTSECHINAA: 0.045
#  GOLD_micro: 0.045
#  IRON: 0.045
#  KOSDAQ: 0.045
#  KOSPI_mini: 0.045
#  KRWUSD_mini: 0.045
#  MSCISING: 0.045
#  MUMMY: 0.045
#  MXP: 0.045
#  RICE: 0.045
#  RUBBER: 0.045
#  TOPIX: 0.045
#  V2X: 0.045

instrument_weights:
  # FX (3 instruments → 1/7 ÷ 3 = 0.0476190476 each)
  EUR_micro: 0.0476190476
  KRWUSD_mini: 0.0476190476
  MXP: 0.0476190476

  # Ags (2 instruments → 1/7 ÷ 2 = 0.0714285714 each)
  RICE: 0.0714285714
  RUBBER: 0.0714285714

  # Equity (11 instruments → 1/7 ÷ 11 = 0.0129870130 each)
  DAX: 0.0129870130
  DOW: 0.0129870130
  EU-BANKS: 0.0129870130
  EU-REALESTATE: 0.0129870130
  FTSECHINAA: 0.0129870130
  KOSDAQ: 0.0129870130
  KOSPI_mini: 0.0129870130
  MSCISING: 0.0129870130
  MUMMY: 0.0129870130
  TOPIX: 0.0129870130
  EU-OIL: 0.0129870130

  # Vol (1 instrument → 1/7 ÷ 1 = 0.1428571429)
  V2X: 0.1428571429

  # OilGas (1 instrument → 1/7 ÷ 1 = 0.1428571429)
  BRE: 0.1428571429

  # Metal (4 instruments → 1/7 ÷ 4 = 0.0357142857 each)
  BITCOIN: 0.0357142857
  COPPER-micro: 0.0357142857
  GOLD_micro: 0.0357142857
  IRON: 0.0357142857

use_instrument_div_mult_estimates: True
#instrument_div_multiplier: 2.1

#
# forecast combination
#
forecast_weights:

# Expensive
  ewmac2_8: 0
  ewmac4_16: 0
  ewmac8_32: 0
  ewmac16_64: 0.3
  ewmac32_128: 0.3
  ewmac64_256: 0.3

forecast_div_multiplier: 1.08
#
# DEFAULT ZONE ---------------------------------
#

#
# Trading rule
#
trading_rules:
  ewmac2_8:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 2
         Lslow: 8
     forecast_scalar: 10.6
  ewmac4_16:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 4
         Lslow: 16
     forecast_scalar: 7.5
  ewmac8_32:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 8
         Lslow: 32
     forecast_scalar: 5.3
  ewmac16_64:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 16
         Lslow: 64
     forecast_scalar: 3.75
  ewmac32_128:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 32
         Lslow: 128
     forecast_scalar: 2.65
  ewmac64_256:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 64
         Lslow: 256
     forecast_scalar: 1.87

forecast_cap: 20.0

# Rule grouping
rule_groups:
    ewmac_fast:
       - ewmac2_8
       - ewmac4_16
    ewmac_medium:
       - ewmac8_32
       - ewmac16_64
    ewmac_slow:
       - ewmac32_128
       - ewmac64_256
style_groups:
    trend:
        - ewmac_fast
        - ewmac_medium
        - ewmac_slow

# Buffer
buffer_trade_to_edge: True
buffer_method: forecast
buffer_size: 0.10

